# Basic settings
app-name: LookUp
version: 'PROTOTYPE-DEV'

# Debugging
want-injector: true

# Logging
log-path: /logs
log-format: 'none'
want-log-formatting: true

# Connection settings
default-address: '127.0.0.1'
default-port: 1492
tls-enabled: false

# Chat settings
want-blank-groups: true

# Security settings

# TODO: Figure out a way to secure these settings
# Do not use any of these defaults in production

hmac-key: '614b4d734f78785a4131733075737832745a456f5a41'
challenge-password: '76b8e2753d9ffc4b93111063d296a8729a3829caaeb3'