# Basic settings
app-name: LookUp
log-path: /logs
version: 'PROTOTYPE'

# Connection settings
default-address: '127.0.0.1'
default-port: 1492

# Security settings

# TODO: Figure out a way to secure a key in production:
hmac-key: 'aKMsOxxZA1s0usx2tZEoZA' # Do NOT use this key in production