# Basic settings
app-name: LookUp
version: 'PROTOTYPE'

# Logging
log-path: /logs
log-format: 'none'

# Connection settings
default-address: '127.0.0.1'
default-port: 1492
tls-enabled: true

# Security settings

# TODO: Figure out a way to secure a key in production:
hmac-key: 'aKMsOxxZA1s0usx2tZEoZA' # Change this key during production