# Basic settings
app-name: LookUp
version: 'PROTOTYPE'

# Logging
log-path: /logs
log-format: 'none'
want-log-formatting: true

# Connection settings
default-address: '127.0.0.1'
default-port: 1492
tls-enabled: true

# Chat settings
want-blank-groups: true

# Security settings

# TODO: Figure out a way to secure a key in production:
hmac-key: '614b4d734f78785a4131733075737832745a456f5a41' # Do NOT use this key in production